from ultralytics import YOLO

model = YOLO('/home/bf-robotics/jazzy0605/kassow_RobotUse/models/best20260603.pt')

model.train(
    data             = '/home/bf-robotics/jazzy0605/surgical_instrument_seg.v1i.yolo26/data.yaml',
    epochs           = 30,
    patience         = 12,
    batch            = 4,
    imgsz            = 1280,
    cache            = 'ram',
    device           = 0,
    workers          = 8,
    optimizer        = 'SGD',
    seed             = 0,
    deterministic    = True,
    cos_lr           = True,
    close_mosaic     = 10,
    amp              = True,
    fraction         = 1.0,
    overlap_mask     = True,
    mask_ratio       = 4,
    dropout          = 0.0,
    pretrained       = True,
    verbose          = True,
    # learning rate
    lr0              = 0.0001,
    lrf              = 0.01,
    momentum         = 0.9,
    weight_decay     = 0.0005,
    warmup_epochs    = 3.0,
    warmup_momentum  = 0.8,
    warmup_bias_lr   = 0.1,
    # loss weights
    box              = 7.5,
    cls              = 0.5,
    dfl              = 1.5,
    # augmentation
    hsv_h            = 0.015,
    hsv_s            = 0.5,
    hsv_v            = 0.4,
    degrees          = 60,
    translate        = 0.2,
    scale            = 0.5,
    shear            = 0.0,
    perspective      = 0.0,
    flipud           = 0.0,
    fliplr           = 0.5,
    bgr              = 0.0,
    mosaic           = 0.0,
    mixup            = 0.0,
    copy_paste       = 0.0,
    auto_augment     = 'randaugment',
    erasing          = 0.4,
    # output
    project          = '/home/bf-robotics/jazzy0605/finetune_runs',
    name             = 'yolo11m_original_params_0610',
    exist_ok         = True,
)
